### ISSUE TITLE
....

### ISSUE THREAD

**Issue by masoudtvi** [Gozargah/gozargah.github.io#68]
با سلام و عرض خسته نباشید خدمت شما عزیزان حامی این روز های سخت ملت. 

خواستم اعلام کنم که  در  اپدیت های جدید مشکلات و باگ هایی مثل قطع شدن ناگهانی کانفیگ ها زیاد دیده شده که با ریستارت هسته xray یا مرزبان برای مدت کوتاهی رفع و حل خواهد شد. خواهشمندم لطف کنید و در پی زحمات قابل ستایشتون این مشکل رو رفع کنید تا با آسایش بیشتری به سمت نسخه های جدید حرکت کنیم 🙏🏻

باسپاس فراوان از شما 
M.TVI

**Comment by iamtheted** [comment]
سلام دوست عزیز 
این مورد رو باید در گیت هاب مرزبان ایشو کنین نه داکیومنت
